### ISSUE TITLE
Get all selected values (including childrens)

### ISSUE THREAD

**Issue by koko-ng** [dowjones/react-dropdown-tree-select#108]
Hi,
Is it possible to get all children values when a parent is selected? Or maybe to get the whole flattened tree and then filter it?
Btw, is it normal that `children` is undefined in `currentNode` or  `SelectedNodes` in the `onChange` callback?

**Comment by mrchief** [comment]
> Get all selected values

The 2nd argument returns this info: `onChange(currentNode, selectedNodes)`

> Is it possible to get all children values when a parent is selected?

It's possible but it needs a little bit of upkeep on your side. 

 - Assign node paths to your tree via an [HOC](https://dowjones.github.io/react-dropdown-tree-select/#/tree-node-paths-hoc)
 - Take the node path (any extra props on the node object are returned as is) to grab the children from your input data.

> Or maybe to get the whole flattened tree and then filter it?

The flattened tree is an implementation detail and not part of the public API. You should not depend on it. Also, there is nothing that exposes the flat tree.

> Btw, is it normal that children is undefined in currentNode or SelectedNodes in the onChange callback?

Yes. `children` prop comes from your original input data. Deleting the prop sacrifices certain optimizations by v8, hence it's marked as undefined since the component doesn't need it after initialization (this keeps the memory requirements light).

Tip: You can look at `_children` prop which contains ids for child nodes. They always follow this pattern: `level-child#` (which repeats as you go deeper). Underscore props are somewhat private, as I'm not sure if they should be part of the public API. So use it with caution.

**Comment by koko-ng** [comment]
Thanks for you answer, I tried your solution with the HOC. It works like a charm :). I put a list of all its childrens on each elements, maybe not the most efficient way of doing this, but it works.

**Comment by mrchief** [comment]
> I put a list of all its childrens on each elements, maybe not the most efficient way of doing this, but it works.


I knew letting misc. props bubble up will come handy some day!  :innocent:

**Comment by FredyC** [comment]
Sorry for reviving the older issue, but I don't get it. If `selectedNodes` contains only top-level nodes and `_children` are non-leaf only, I am confused how can I get those selected leafs? Even if I store node paths there, I still don't know which leafs are selected. What am I missing, please?

**Comment by mrchief** [comment]
> If selectedNodes contains only top-level nodes and _children are non-leaf only, I am confused how can I get those selected leafs? 

If you select a top-level node, it implies all children are selected. Does this help clear the confusion?

**Comment by FredyC** [comment]
@mrchief So, in other words, I have to loop through original data and find the selection on my own? That's not very friendly considering that selection is somewhere in the component since it has to render those checkboxes :/

**Comment by mrchief** [comment]
> Point is that our backend solution expects IDs for all selected nodes so it doesn't have to crawl through the relations first.

Right. I've use cases where it needs ids for children and cases where just the parent id is sufficient. So that's more of a business decision which is why the component doesn't make it. 

> considering that selection is somewhere in the component since it has to render those checkboxes

The component doesn't preserve the tree structure. It flattens it and uses pointers to find hierarchical information. So in a sense, the component would have to do the same recursion to construct that. 

> I have to loop through original data and find the selection on my own?

Again, you can choose your own implementation here. If looping sounds unappealing, you can follow the design outlined [here](https://github.com/dowjones/react-dropdown-tree-select/issues/100#issuecomment-388388240). Combined with something like [lodash.at](https://lodash.com/docs/4.17.11#at); you can then retrieve the children from your input `data` object and do whatever you need with it.

**Comment by FredyC** [comment]
> The component doesn't preserve the tree structure. It flattens it and uses pointers to find hierarchical information. So in a sense, the component would have to do the same recursion to construct that.

That's totally fine, a tree structure is not necessary for selection, on the contrary, it would be in away as it would have to be recursively looped through. I see it more like an inconsistency in the API. The `onChange` has the second arg called `selectedNodes`, but there is no mention (or I did not find it) that it's only some nodes. One would expect that by selected nodes you mean all nodes visible in the tree that are currently checked.

It doesn't matter now, our backend guys did the hard job here and are finding those relations after all. For the future, we will write own component that's more up to the task. 

I am definitely grateful that you made this. It helped us to cross the deadline scenario, but it's too much opinionated and it's not clear how to approach different cases. Also, I find the approach of using `componentWillReceiveProps` to start from the scratch as fairly confusing. Not only it's a deprecated method, but it forces burden of memoizing on the user after spending hours figuring out why it behaves weirdly.

**Comment by mrchief** [comment]
> Also, I find the approach of using componentWillReceiveProps to start from scratch as fairly confusing. Not only it's a deprecated method, but it forces the burden of memoizing on the user after spending hours figuring out why it behaves weirdly.

It's not evil! :)

This is a classic case of the FUD this so called deprecation is causing. This is not even a deprecation - it's more like forcing people to take notice of the fact that using this method needs to be thought out carefully. In some future version of React, async updates might cause issues with `cWRP`. By that time, I'm also positive that we'd have some valida alternative to go to (`gDSFP + cDU` is not that). 

There are valid uses cases for using `cWRP` and this component is not only aware of those, but also uses them appropriately. This is not really deprecated. React 17 will still support them as long as they are prefixed with `UNSAFE_`. 

Anyway, for the timebeing, there is no alternative. See this https://github.com/reactjs/reactjs.org/issues/2428

A newer version of this component will rename them so that they continue to work in React 17. The warning also comes from one of the dependencies which again, is one of the valid use cases for using `cWRP`.

I'm glad this helped you and I'd welcome any PRs that you think will help improve this component.

**Comment by FredyC** [comment]
> By that time, I'm also positive that we'd have some valida alternative to go to (`gDSFP + cDU` is not that).

Well, we already do have that, it's called `React.useEffect` ;) Lifecycle methods are generally the wrong concept. Thinking in matters of state synchronization works generally better.

> I'd welcome any PRs that you think will help improve this component.

Perhaps rewrite to Hooks? As long as it stays in classes, I am not interested in contributing. I hate those things :)

**Comment by mrchief** [comment]
I was fortunate enough to attend the very conference where hooks were introduced so yeah, I know a thing or two about them. 

`useEffect` is not the answer. Not even close. But, I'm happy to be wrong here, so send me an example of what you have in mind.

> Lifecycle methods are generally the wrong concept. 

Citation please?

> Thinking about state synchronization works generally better. 

Care to elaborate? Not in general, but in relation to how it can solve my blockers as stated in issue 2428?

> because classes will be just gone one day

Folks on React core team seem to think contrary to this but you're free to have your own beliefs. I personally am not a fan of JS classes but they do serve a purpose. Hooks are just a tool, and like every tool, it has its uses. Same with classes. 

> Perhaps rewrite to Hooks? As long as it stays in classes, I am not interested in contributing. I hate those things :)

Your earlier comments seem to suggest the documentation could use some improvements. I did start working on a newer version that uses hooks. But like I mentioned earlier, issue# 2428 is a blocker. Anyway, if you're interested in solving those blockers, do take a look at the [`hooks`](https://github.com/dowjones/react-dropdown-tree-select/tree/hooks) branch.

**Comment by FredyC** [comment]
> > Lifecycle methods are generally the wrong concept.
> 
> Citation please?

I am sure many people said a similar variant of it, but I am not keeping links to that anywhere to that :) Let's consider it my personal citation. I've always hated classes and was avoiding them as much as I could even before hooks. Most of my codebase was functional components when they were introduced and garbage was hidden in classes.

> > Thinking about state synchronization works generally better.
> 
> Care to elaborate? Not in general, but in relation to how it can solve my blockers as stated in issue 2428?

There was a rather famous tweet from I believe Michael Jackson that established this term but cannot find it either now :) It's mostly about a different mindset. Instead of thinking in terms of the lifecycle you are basically running side effects based on particular state change. That creates a natural flow and allows for composition.

> Folks on React core team seem to think contrary to this but you're free to have your own beliefs.

Once again, there was a quite vast twitter thread with Dan Abramov and one of the questions was future of the classes. Obviously, they won't drop it now because they have huge code base with it. But he clearly stated that once they will surely be a thing of the past. But that's not relevant now.

**Comment by mahesh-insight** [comment]
@mrchief Hope you are doing well.
In several places, I saw your resolution comment. Really Appreciate it.

Assign node paths to your tree via an [[HOC]](https://dowjones.github.io/react-dropdown-tree-select/#/tree-node-paths-hoc) - I am done with this point.

Take the node path (any extra props on the node object are returned as is) to grab the children from your input data.
Not getting this actually. How to check the specific value from the node path.

@koko-ng I hope you are doing well too. Only you are the one who got success. Please help me as well to achieve this.

The Tree Data comes from the API.

![Screenshot 2023-11-04 at 11 50 23 AM](https://github.com/dowjones/react-dropdown-tree-select/assets/144375931/d5c5ac3a-5931-4cd2-85f7-c32eb3889e6b)

On the selection of the parent element - AKS - I need the related children value - deploymentNode
![Screenshot 2023-11-04 at 11 52 14 AM](https://github.com/dowjones/react-dropdown-tree-select/assets/144375931/9e54b0ea-29f3-41bc-aee7-6c7247f8e3ef)


Looking for a positive revert.
