### ISSUE TITLE
Feature Request : Add showDropdown prop to readme

### ISSUE THREAD

**Issue by SeunginLyu** [dowjones/react-dropdown-tree-select#144]
I wanted the dropdown-content to be rendered regardless of the dropdown-trigger status. (I wanted to see the tree on init bascially). I sort of did this by adding the showDropdown prop as I did below. 

`<DropdownTreeSelect
          showDropdown={true}
          data={treeData}
          onChange={onChange}
          onAction={onAction}
          onNodeToggle={onNodeToggle} />`

Could you maybe add this prop to the documentation and perhaps add an option to make the dropdown-content to be always rendered and visible?

**Comment by mrchief** [comment]
I wasn't sure if there would be enough use cases to make `showDropdown` a supported prop, so I kind of toyed with it - which is why it's undocumented. I think it's safe to take it out of its beta phase (so to speak 😉 ) and make it documented.

Regarding the always visible, you can use `showDropdown={true}` in combination with CSS to keep it always visible - I'm assuming you don't want to show the toggle arrow in your case - so you can/should probably hide it via CSS anyway.

**Comment by mrchief** [comment]
If you want to, feel free to send a PR for the docs.
