### ISSUE TITLE
Selecting top level returns children: undefined

### ISSUE THREAD

**Issue by danielsetreus** [dowjones/react-dropdown-tree-select#149]
Great plugin - one issue:

Selecting a top level node trigger the `onChange` callback, however the `children` attribute of `selectedNodes` is not set (undefined).

It would help a lot if the selected top level node (with all its children implicitly selected) could contain the list of all children, as you would not have to look that up again from the original data set.

There is a `_children` attribute that contains a list of the child IDs - but that doesn't really help much.

Since there is a `children` attribute ant its `undefined` I suspect that either I am doing something wrong, or there is a bug.

**Comment by mrchief** [comment]
There is a reason for the said behavior. The component works on a flat list<sup>1</sup>, once it's initialized - so it cannot pass the selected children without traversing the list and gathering the children and assembling them back as a tree. It maintains pointers to child nodes via `_children` and simply bubbles them up so that the caller can do that if desired. This keeps the performance cost (of traversing the tree) to a minimal for everyone.

You can check out this [answer](https://github.com/dowjones/react-dropdown-tree-select/issues/108#issuecomment-391836044) for a workaround.

If you have suggestions on how we can improve this, then please let me know.

<sup>1</sup> -  this is done purely for performance
