### ISSUE TITLE
keepTreeOnSearch missing parent nodes

### ISSUE THREAD

**Issue by JKapostins** [dowjones/react-dropdown-tree-select#155]
I'm using version 1.12.4 and having troubles with keepTreeOnSearch={true}. When a search is applied, only the nodes that contain my search text are drawn (no parents). It appears that the logic is partially working because the nodes that contain my search text have the proper indentation. 

**Expanded tree with no search criteria**
![expandedtree](https://user-images.githubusercontent.com/7006862/44113403-ef383ebc-9fd5-11e8-8e0f-74a7696f0d5a.PNG)

**Tree with missing parents**
![searchedtree](https://user-images.githubusercontent.com/7006862/44113409-f45c2e9e-9fd5-11e8-8817-c883fd8c0099.PNG)

**Functional [demo tree](https://dowjones.github.io/react-dropdown-tree-select/#/story/with-bootstrap-styles) which doesn't appear to use infinite scroll**
![workingdemo](https://user-images.githubusercontent.com/7006862/44113415-f69eff2e-9fd5-11e8-86f9-328b37f733f1.PNG)

**Comment by mrchief** [comment]
This looks like a regression that got introduced in 1.11.2. I can see it working prior to that. Need to investigate.

**Comment by MomchilGorchev** [comment]
Hi all, thanks for the cool package!
Im getting the same issue with v1.12.4
Any findings/workarounds?
Regards

**Comment by mrchief** [comment]
@MomchilGorchev I haven't had any time to dig into this. Let me know if you find anything. I'm planning to look into it by this weekend.

**Comment by JKapostins** [comment]
Any news on this @mrchief ?

**Comment by mrchief** [comment]
Working on it, hang in there!

**Comment by mrchief** [comment]
I traced the root cause of it and it seems to happen because infinite-scroll and old logic are not deeply compatible. I'm wondering if I should invest time in finding a fix (which would require significant changes to existing logic) or if I should change the existing approach (of how dom nodes are painted).

A slightly longer explanation requires delving into component's development history. 
Initially, when I built this component, I believed that keeping the DOM nodes and changing their attributes to show/hide them while searching will be more performant than painting only matched nodes. What I have learned since then is my initial understanding was flawed, and completely false apart for large trees. Creating/destroying 100 DOM nodes is hardly perceptible and is actual more memory efficient since we only have 100 nodes instead of as many as the tree has.

I think I should take a stab at doing the later as that'd not only fix this issue, but will also result in a performance boost.

**Comment by MomchilGorchev** [comment]
Ok, this sounds good, any quick'n'dirty thing to do in the mean time?
Thanks

**Comment by JankiAmrutia** [comment]
@mrchief Thank you the update on the issue. 
I understand the compatibility issue with infinite scroll and displaying the matching parent of selected node. Can you please explain as what is the actual functionality that you are trying to implement to fix the issue ?

**Comment by mrchief** [comment]
@MomchilGorchev You can try using v1.11.2 or maybe v1.11.1 if that serves your purpose.

@JankiAmrutia it's a long story. 

 - In the beginning, there was no `keepTreeOnSearch`, no infinite scroll, so life was simple. When you search, the tree manager figures out matching nodes, sets them to display visible and hides the rest.

 - With `keepTreeOnSearch`, things get slightly complicated - since now you need to keep track of parent nodes, so that you can show the hierarchy.

 - With infinite scroll, things got even more complicated - since now you need to keep track of what's loaded and what not, and paint the visible nodes that are visible _within the viewport_ and fetch the _not-yet-painted-nodes_ as the user scrolls and paint them. 

So I'm exploring options as to how this can be fixed, and if possible, be made more performant.

**Comment by mrchief** [comment]
As a workaround, I reverted the change introduced in v1.11.2. That seems to have fixed this issue.

**Comment by JKapostins** [comment]
Thanks for looking into this @mrchief. I just upgraded to 1.12.7 and gave it a go. It's working perfect when searching the first 100 nodes in my tree, however when searching a node beyond the 100 mark I get a blank tree returned. Have you tested this on a large data set?

I'll post more details on my specific problem if you aren't able to reproduce the issue.

**Comment by mrchief** [comment]
I don't think I did. Let me try tonite and get back to you.

**Comment by jonsvez** [comment]
Seems to be broken for large trees on search. Shows en empty result set even though you search for strings that exist in the tree. The weird thing is, I upgrade from 1.12.5 to 1.12.7 and i broke, but when I go back to 1.12.5 its still broken, which leads me to believe that it might be a dependency of this project that changed, or something like that.

If I redeploy an old build of my app, it works :D . So I think it might not be your code.

**Comment by jonsvez** [comment]
Note that my problem has nothing to do with keepTreeOnSearch, its just search in general that seems broken but it could be the same reason

**Comment by mrchief** [comment]
This is useful information. Luckily, we have only 3 dependencies. I can rule out `array.partial` since I haven't pushed anything there. `classnames` seems unlikely. Let me see if infinite scroll had any changes.

**Comment by mrchief** [comment]
**With old node_modules** (old as in the day 1.12.7 was released)
![2018-10-11_17-46-29](https://user-images.githubusercontent.com/781818/46836481-9b02e900-cd7f-11e8-89ae-8fc354e1f631.gif)

**With latest node_modules**
![2018-10-11_18-04-50](https://user-images.githubusercontent.com/781818/46836612-35fbc300-cd80-11e8-8cb3-b9e7a2378bfc.gif)

**latest node_modules, `keepTreeOnSearch = true`**
![2018-10-11_17-57-51](https://user-images.githubusercontent.com/781818/46836497-b53cc700-cd7f-11e8-8861-366403c6c015.gif)

I can't reproduce it locally. One thing I did notice is that the newer bundle is sluggish on IE - I think this may be caused by dev dependencies but not sure which one. I'll try to pin the versions and try again. 

Meanwhile, if you guys can provide some reproducible repo, that'd be great.

**Comment by jonsvez** [comment]
I can reproduce it on the demo site, search for rektangel10-1 works fine, its the first node in the tree, and cihildren of this node can also be searched.

But If you search for something further down, like *rektangel12-1*, you get an empty result set.

**Comment by mrchief** [comment]
This seems like something else then. May not be the same issue. Let me take a deep dive.

**Comment by jonsvez** [comment]
seems like it works in 1.12.5 now, idk what i did yesterday.

**Comment by mrchief** [comment]
@jonsvez It's probably your data. This bug can happen if your first match is at least 100 nodes down like _rektangel12-1_. Anyway, I think I fixed it for good. Gonna run some more tests and if everything checks out, a release soon.

**Comment by mrchief** [comment]
@JKapostins @MomchilGorchev @JankiAmrutia @jonsvez Please try with v1.12.8-beta.1 and let me know.

**Comment by jonsvez** [comment]
**1.12.8-beta.** seems to work great ! tried with **keepTreeOnSearch** which also worked

**Comment by jonsvez** [comment]
I do not use **keepTreeOnSearch** so I'm not a good tester for that, but regular search seems to work great.

**Comment by JKapostins** [comment]
@mrchief v1.12.8-beta.1 is working perfect!

**Comment by mrchief** [comment]
This is now available in version 1.13.0

 - [npm package](https://www.npmjs.com/package/react-dropdown-tree-select)
 - [GitHub release](https://github.com/dowjones/react-dropdown-tree-select/releases/tag/v1.13.0)
