### ISSUE TITLE
Toggle Dropdown event fires issue - Dropdown collapses and expands even i don't click on dropdown.

### ISSUE THREAD

**Issue by JankiAmrutia** [dowjones/react-dropdown-tree-select#175]
@dowjones-admin  
Steps to reproduce -:
1. Open any tree from demo url.
2. click on dropdown to expand and then collapse it again.
3. Now click anywhere outside the tree; Dropdown gets collapsed again. 

As per my view, dropdown should not collapse if user has not clicked on dropdown.

In my scenario , i have a large tree on left and a table on right. If i click on dropdown once and open it again, and now try to click on any item in the table, the tree on the left collapses. There is no function that is exposed to prevent or stop this event. 

Can you please explain if there is a solution to this ? 

@dowjones-admin Appreciate your efforts.

**Comment by mrchief** [comment]
> Now click anywhere outside the tree; Dropdown gets collapsed again.

This behavior is to mimic the behavior of a normal dropdown control. In addition, since this is a multi-select dropdown, it stays open until you click outside. In single select mode, it'll close after first selection.

> In my scenario , i have a large tree on left and a table on right. If i click on dropdown once and open it again, and now try to click on any item in the table, the tree on the left collapses. There is no function that is exposed to prevent or stop this event.

It looks like you need a drawer instead of a dropdown. While that was not the use-case this component was built for, I've seen this feature requested before as well. 

There is an undocumented property `showDropdown` that will cause the component to render with the dropdown in an expanded state. Let me know if that helps.

If not, and if you'd like to contribute to this feature, I'm open to PRs.

**Comment by JankiAmrutia** [comment]
Ok Thank you for you reply. I might contribute for this and raise a pr.

**Comment by JankiAmrutia** [comment]
Closing the issue as this is not an issue as per the use case of the component.
