### ISSUE TITLE
Once onChange(...) dispatches redux action, it doesn't update tree select component correctly

### ISSUE THREAD

**Issue by ariel-lee** [dowjones/react-dropdown-tree-select#195]
**Describe the bug**
I am facing the same issue as https://github.com/dowjones/react-dropdown-tree-select/issues/107 

When I pass `onChange` handler function that dispatches a redux action, the component doesn't render the list of checked items correctly. Ideally, I should see `value` props to send the list of selected items instead of letting the component keep track of its own `tags` state. Is there any workaround or correct way to feed redux action handler to the component while not breaking its behavior?

**To Reproduce**
Pass on handler function that dispatches redux action to update app's form to `onChange` props.

**Expected behavior**
Redux action is dispatched correctly, updating the store, while tree selector updates itself with correct checked items and list of tags

**Comment by mrchief** [comment]
Hi @ariel-lee, thanks for taking the time to describe your problem. 

If I understand your problem correctly, you want the component to pass you the values, tags, etc. and you want to take care of setting selected state, tags via redux actions - am I right?

If yes, then I'm afraid that it is not something the control supports or allows. This is a design decision, and it was done so for the following reasons:

 - so that the component doesn't _need_ to depend on redux or any external store management library.
 - so that the component can be **_efficient_** and **_independent_** about its internal state management without breaking or affecting its consumers.
 - the typical redux lifecycle of `component > notify store > store dispatches action > reducer updates props > component is passed the updated props > component re-renders` is highly redundant in this case - since the component knows what happened, and what it should do accordingly. There is simply no need for it to tell redux for redux to tell itself what happened and what to do. 
 - *tree* is a complex data structure and can get heavy. The component performs initialization tasks to simplify and optimize tree handling, searching, etc.; so you don't want to redo this every time the toggle or checked state changes (since your data didn't change, just it's appearance).

I love and use redux heavily in my apps; in fact, this component was created for consumption in an exiting redux based app. State management is a much-debated topic in React community, and there are many schools of thoughts regarding how it should be done. While designing this control, we did not see any good reason as to why we would need anything beyond what JavaScript (object props) and React's internal state (`setState`) provide. In Dan Abramov's [own words](https://medium.com/@dan_abramov/you-might-not-need-redux-be46360cf367)

> For example, consider a React component with local state:
> 
> It is perfectly fine as it is. Seriously, it bears repeating.
> 
> _Local state is fine._
> 
> The tradeoff that Redux offers is to add indirection to decouple “what happened” from “how things change”.

I subscribe to that 100%. _**As a consumer**_, I don't want to know how the control does its magic, nor should I be required to handhold or babysit the component. I want to _use the component_ precisely because I don't want to deal with what it does; otherwise, I could just write my own! When I use a component, it should just work!

And so, that is what this control aims to do - provide a service. The `onChange` and other event handlers are to notify the caller about what happened so that the caller can use those events to record or react accordingly. You can use Redux in your app just fine, but the control doesn't need Redux to manage itself.

Now, if I am to take a somewhat educated guess, what you're probably facing is the component re-render issue, when something in your redux store changes. If so, you can implement this HoC solution: [prevent-re-render-on-parent-render-hoc](https://dowjones.github.io/react-dropdown-tree-select/#/story/prevent-re-render-on-parent-render-hoc), and that should take care of those pesky re-renders.

**Comment by ariel-lee** [comment]
Thank you @mrchief for a very detailed explanation of your design decision. I agree that local state is fine, but I was trying to use the component in an existing application built using redux. I appreciate your help and design decision made with thoughts 👍

**Comment by mrchief** [comment]
Did the HoC solution work for you?

**Comment by alextaymx** [comment]
let say i have to update user details , initially there is a defaultValue to be displayed in the component, but i need the internal state/ selected value to reflect on my own use state (so i can submit the selected value in form onSubmit function), is it possible?

**Comment by mrchief** [comment]
@alextaymx could you please start a new discussion or is your cases related to this issue?
