### ISSUE TITLE
Dropdown closes when opening parent ( in long list)

### ISSUE THREAD

**Issue by motiko** [dowjones/react-dropdown-tree-select#198]
**Describe the bug**
In Firefox when the list is long. After scrolling down until more nodes are loaded (> 100) clicking on a parent node will close the dropdown.

**To Reproduce**
Use [this](https://codesandbox.io/s/0qjl5mx4v0) demo.

1.     Scroll down until more nodes are loaded.
2.     Click on the + to open a parent
3.     Dropdown is closed in Firefox 

**Expected behavior**
The dropdown should stay open after expanding a parent node in all browsers.

**Environment (please complete the following information):**
 - Firefox 63.0.3 (maybe others but not happening in chrome)

**Additional context**
The parent node has to be after 100 nodes.

**Comment by mrchief** [comment]
This seems like the same issue as #148.

**Comment by motiko** [comment]
Wow thank you for your quick response let me know if i can help

**Comment by mrchief** [comment]
Well, we need to find a permanent fix for this. I'm thinking about alternative ways of detecting outside click or finding the root cause of firefox's behavior. Maybe it's a browser bug? Anything you can think of in finding the root cause or coming up with alternate solutions will be a great help.

**Comment by motiko** [comment]
What is your opinion on using [react-click-outside](https://www.npmjs.com/package/react-click-outside)? I have a PR ready in case you want to go this way?

**Comment by motiko** [comment]
> I'm not sure why the workaround is not working in the latest version. Will have to dig deeper.

From what i see the lines added in #178 
```
let easyPath = e.path || (e.composedPath && e.composedPath());
if (easyPath) return easyPath
```
are not in the updated develop.

**Comment by mrchief** [comment]
Thanks for looking into it! I'm generally averse to increasing bundle size by adding another dependency, especially since react-outside-click employs the same `node.contains` method to check if the click should close the dropdown. 

The `easyPath` check was added but then removed since we found that the code worked without it just fine. I'm sure the discussion is somewhere in old issues/PRs. 

I'm curious to see why Firefox behaves differently than the spec. We can always add the fallback or employ another technique if we are running short on time.

**Comment by motiko** [comment]
Somehow related, working with click event has some accessibility issues see this [SO answer](https://stackoverflow.com/a/38317768/1029351). Consider using [focusout](https://developer.mozilla.org/en-US/docs/Web/Events/focusout) instead.
I can open a feature suggestion issue if you prefer.
