### ISSUE TITLE
Create a better doc project

### ISSUE THREAD

**Issue by mrchief** [dowjones/react-dropdown-tree-select#222]
Currently, the documentation site `https://dowjones.github.io/react-dropdown-tree-select/` is housed under `docs` folder. 

The advantages of this approach are:

 - easier to do at the start of the project
 - one package.json for dependencies (easier to manage)
 - examples closer to source
 - easier to test changes while developing locally

Disadvantages

 - biggest one being the conflicts with `docs/bundle.js` which needs to be resolved manually
![image](https://user-images.githubusercontent.com/781818/54403355-14dc2d00-46a6-11e9-9dd4-82f48eb44ab7.png)
 - `devDependencies` in package.json is a bigger list than what's needed
 - not easy to preview new docs in a PR unless merged.
 - no integration tests
 - need for workarounds like `"demo": "rimraf ./docs/bundle.js && ...`

It'd be nice to have docs project that reduces or eliminates the disadvantages while preserving the advantages (or offering better alternatives).

**Comment by ellinge** [comment]
What about not compiling the bundle at all and using babel-loader. That should be possible right?

You need to reference an entry point in the src-dir also I guess so that imports are found. Not sure if that's available relatively though. 

Since it already does not work in IE11 for example I think it would mean no difference in browser combability.

**Comment by ellinge** [comment]
What about not compiling the bundle at all and using babel in browser, see https://babeljs.io/setup. That should be possible right?

Since it already does not work in IE11 for example I think it would mean no difference in browser combability.

You probably would need to change the root to master instead on the github page so that src is available relatively.

I have only used webpack + babel-loader so not sure this actually solves everything but in theory it should.

**Comment by mrchief** [comment]
> What about not compiling the bundle at all and using babel in browser, see babeljs.io/setup. That should be possible right?

It's possible but what is the performance like?

> Since it already does not work in IE11 for example I think it would mean no major difference in browser combability.

The component itself supports IE 11 but unfortunately, react-story's dependencies do not. A newer version of it was in the works but that wasn't stable at the time of writing. That said, the doc site did work in IE 11 in the past. I'm not sure at what point it broke.

But that highlights another point - we should be supporting IE 11 - maybe a degraded experience but the doc site should come up.

I would like the doc site to be statically generated so that it's blazing fast. I was looking at https://github.com/pedronauck/docz as it allows MDX and a playground. I'd still keep CodeSandbox examples but they do not auto-update with new releases, so I'd like to minimize relying on them for playground pages. 

I've looked at storybook in the past but it wasn't flexible at that time. But it does offer integration tests which are a plus. Everything is an option at this point!

**Comment by ellinge** [comment]
Well it still looks like you need some build output for that. That is the main issue right? Static files which is included in the source code and causes merge conflicts. Then the only thing working is running the compile in the browser?

Otherwise it needs to be separated out from the source and handled like more like the dist build output.

**Comment by mrchief** [comment]
> Well it still looks like you need some build output for that. That is the main issue right? Static files which is included in the source code and causes merge conflicts. 

Yes, that's the main issue. 

> Then the only thing working is running the compile in the browser?

There are alternate ways. E.g use <username>.github.io repo and move docs there, or use sites like Netlify. For creating the actual site, docz or docusausrus or similar can be used.

**Comment by mrchief** [comment]
Interesting convo: [What is the best documentation tools for a React Library?](https://spectrum.chat/react/general/what-is-the-best-documentation-tools-for-a-react-library~d3649a8b-9c62-4b58-a504-3626cd60eec1)

**Comment by mrchief** [comment]
This seems like a good fit: https://compositor.io/x0/

**Comment by mrchief** [comment]
Having second thoughts on compositor. The libs have not been active for almost a year.
