### ISSUE TITLE
Migrate away from unsafe methods

### ISSUE THREAD

**Issue by ellinge** [dowjones/react-dropdown-tree-select#234]
The component should migrate away from unsafe methods. It uses:
- componentWillMount
https://reactjs.org/docs/react-component.html#unsafe_componentwillmount
- componentWillReceiveProps
https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops

When migrating it would also be nice if the component did not rerender if it will lead to the same state. But that's a hard one I guess since it depends on so many things. It also states that you should put this in a [HOC](https://github.com/dowjones/react-dropdown-tree-select/blob/develop/docs/HOC.md#prevent-re-render-on-parent-propstate-changes). But perhaps there's some easier way to avoid it. From the top of my head compare `JSON.stringify({ prevState.tree, prevState.tags })` with `JSON.stringify({ nextState.tree, nextState.tags }) `or similar.

**Comment by mrchief** [comment]
> The component should migrate away from unsafe methods

That would require a certain version and up for React. It's doable but it's another speed bump for anyone who's trying to use this package. 

I'm pretty sure we're clear of any unsafe practices though, so I'm holding off until React 17 is released and we make a major release for that. That said, if these methods don't work in recent React versions, then we need to do this sooner than later anyway.

React 15 is already incompatible I think (due to actions returning an array instead of a single element) but I don't want to force people to upgrade their React as long as I can avoid it. 

> When migrating it would also be nice if the component did not rerender if it will lead to the same state. But that's a hard one I guess since it depends on so many things.

Yes, that could be an expensive op hence we don't do it by default. We do use `PureComponents` which do a shallow check to mitigate some of those renders. However, just because React does a render it doesn't mean DOM gets updated - the diff is what matters ultimately so I'm not too bothered with the status quo.

**Comment by ellinge** [comment]
I guess we can close this one until then.
The main problem we have is that you have to keep a updated node-collection with not only the label/values but also which ones are checked and expanded (by subscribing to events). It would have been easier if it were separated more, I guess.
One solution would have been to store the expanded and checked state and restore it when receiving new props. But we would have to reassure it was the same node-data as before and I guess that’s where it gets hard. Who should win, the node-props or the state etc.

**Comment by mrchief** [comment]
You're mirroring my thoughts here. I've debated this topic time and again. We use this component internally and in some cases, we can't avoid the re-render of the main component. 

We use the tree node path HOC approach to easily update the state on the call site. When a node change event happens, the `node` argument passes the node path back and using that path, we can easily dereference (e.g. using `lodash.get`) the right node in the tree. This tree is stored in the state so when the component re-renders due to state change on the parent, it gets this updated tree object and is able to restore the state correctly. We use redux as the global state store though. But the idea is the same. 

I guess we could bake this in the component but at the cost of extra complexity and a bigger bundle size. We can, however, bake it into a HOC and maybe bundle that in the package. It'd still increase the bundle size but tree shaking should be able to take care of that. Something like:

```
import { TreeNodePath } from 'react-dropdown-tree-select/HOC'
// or
import { PreventRerender } from 'react-dropdown-tree-select/HOC'
```

(I know the names are not the best one but you get the idea)
