### ISSUE TITLE
texts props is not working

### ISSUE THREAD

**Issue by ioannisth** [dowjones/react-dropdown-tree-select#263]
I want to change the placeholder text, so I tried texts={{ placeholder:'Search' }} in the props.
However , this does not seem to have any effect, but while looking through the minified bundle. I was able to find out that you can change the placeholder text using placeholderText={'Whatever'} as a prop.

**Comment by mrchief** [comment]
@ioannisth Hey, sorry for this confusion. `texts` won't work until the next major version gets released. It's a breaking change and we're in the process of finalizing all breaking changes so that they can be released together. 

The next version should be released soon but if you want something urgently, I can maybe release the changes under `@next` tag.

**Comment by mrchief** [comment]
@ioannisth 	Just released v2.0.0 which fixes this.

**Comment by ioannisth** [comment]
thanks! :)

**Comment by ioannisth** [comment]
@mrchief unfortunately , this has broken again

**Comment by mrchief** [comment]
@ioannisth Can you please open a new issue with steps to reproduce?
