### ISSUE TITLE
Workarounds for "const" being not supported on old version of Safari

### ISSUE THREAD

**Issue by davidrenne** [dowjones/react-dropdown-tree-select#267]
Hi there,

I have a customer complaint on our product now that we have implemented v2.0.2 of this library.  The customer has a very old version of safari (I can give you the version at a later comment if you need it) which cannot parse the javascript line of code inside of react-dropdown-tree-select.js

```
e.exports=function(e,t){const n=e.filter(t);return 0!==n.length&&n.length!==e.length
```

It cannot parse it due to the fact that const shows up in the minified code.  If I change it to var and recompile my package.json, safari is able to parse all the bundled javascript of the entire app and is able to render on an older version of safari.

So I am having a hard time finding this filter function in all of the node_modules or in your source code.  Does anyone have any idea which dependency is outputting this const so I can fork it and put it to a var instead of a const?

I thought it might be a copy of react or something because I see SECRET_DO_NOT_PASS_THIS_OR_YOU_WILL_BE_FIRED around that part of the code.  Any help in understanding where this const declaration is coming from will help me greatly.  I just cannot seem to find any resemblance of code matching that anywhere searching for .filter() doesnt show up at all in my searches.

Thanks for any insight!

**Comment by mrchief** [comment]
This is happening since that older version of Safari doesn't support ES6. There could be a lot of dependencies outputting this. 

This component has very few dependencies:

https://github.com/dowjones/react-dropdown-tree-select/blob/866af6ee0a79d0ea211ba6b5690143fd602ddd4f/package.json#L45-L49

but they, in turn, could have a dep tree that might bring in ES6 code. 

Although not recommended, you can also try transpiling `node_modules` to ES5 which may help.

**Comment by mrchief** [comment]
Also, v2 didn't bring in the new version of dependencies, but the carat range might install newer versions. You can try pinning down the version (like `"react-infinite-scroll-component": "4.0.2"`) and see if that fixes the problem. 

You may try forking this project and transpiling to ES5 (since this project also transpiles to ES2015 which may output `const`). 

Now if you didn't have this problem in an older version, then let me know the version and I can take a deeper look as to what changed. The transpilation and dependencies haven't changed in a long time so I'm curious.

**Comment by davidrenne** [comment]
Do you know where in the webpack configuration i can change it to compile down to an earlier version of ecma script?

**Comment by mrchief** [comment]
You can specify those in the `.babelrc` for this repo. You can also pass those to babel-loader too if you don't wanna create a babelrc in your repo.

**Comment by ellinge** [comment]
Probably from node_modules\array.partial\index.js
`Line 3:   const some = arr.filter(func)`

**Comment by davidrenne** [comment]
@ellinge ill check it out.  How could my searches not find it in node_modules.  So weird!  You rock!!

**Comment by ellinge** [comment]
I checked the source in the mapping file instead before searching. Perhaps you searched for the compiled code? It's @mrchief package I later noticed so he could probably fix it easily,.

**Comment by mrchief** [comment]
I wanted to avoid transpilation in there. Guess I could just use `var`? That feels _dirty_. 😬 

I wonder if that's the only dep causing the issue. One would think anyone out of the gazillion packages would be the culprit, anyone but you 😆.

**Comment by ellinge** [comment]
Well it matches the transpiled code and the only instance of const found so I think we our culprit 😄
