### ISSUE TITLE
Add possibility to use custom predicate/filter when searching nodes

### ISSUE THREAD

**Issue by ellinge** [dowjones/react-dropdown-tree-select#269]
We have found a use case where we want to have "shortcut"-match on items which is not displayed as a label on the item. How about an optional additional field, a.k.a, hidden label, on the passed node data which the searchterm also is filtered against?

**Comment by ellinge** [comment]
Checked what react-select offered and they allow a custom filtering func instead, which perhaps could be a better option instead of the additional prop. A func which would be passed the current searchTerm and node to filter on. Could then be used to filter on a custom props passed or similar.

**Comment by mrchief** [comment]
So say you have a list of companies and when someone types `ABC`, it should match `Another Boring Company`?

So something like:

```
node: {
  label: "Another Boring Company",
  searchAlias: "ABC"
  /* other props */ 
}
```

I say `searchAlias` as it seems to be a little more informative about its purpose rather than `hiddenLabel`.

I like the idea of a custom func too as that's much more flexible and extensible.

**Comment by ellinge** [comment]
Agree on custom filter func being for flexible, then it could be used on any custom prop the user has.
And yes, that would be a perfect use case with acronyms.

**Comment by mrchief** [comment]
Right, a custom func allows the caller to do more than a simple string matching (e.g. enabling fuzzy matches). 

Acronym is a coincidence, I didn't exactly mean to imply that. :)
