### ISSUE TITLE
How to disbale search box

### ISSUE THREAD

**Issue by verchika** [dowjones/react-dropdown-tree-select#287]
As my feature requirement,I don't want to search dropdown values

**Comment by mrchief** [comment]
There are a few options depending on details of your use case:

 - you can render it in `[readOnly](https://github.com/dowjones/react-dropdown-tree-select#form-states-disabledreadonly)` mode
 - you can hide the input box entirely via css `.search { visibility: hidden; }`

If you want to have it shown but still have it disabled while allowing checkboxes/selection to happen - well that's a use case I didn't think of. We can add it but since this component is usually meant to render trees and by nature, trees tend to be tedious to navigate; having a search box helps. So I'm curious about your use case as to why you want it disabled. :)
