### ISSUE TITLE
Don't hide tree items if they contain the search term

### ISSUE THREAD

**Issue by sniggitysnax** [dowjones/react-dropdown-tree-select#291]
**Is your feature request related to a problem? Please describe.**

Currently, if I'm searching for an item, I am returned some items that contain the search term but they are hidden with the .hide class. 

EX: https://codesandbox.io/s/using-material-design-with-react-dropdown-tree-select-9sdiq
Search for iway. It is returned but the parent is grayed out. I would expect that any element which contains the search term be visible (not .hide)

**Describe the solution you'd like**

When you search for an item, there may be scenarios in which a taxonomy is used that contains multiple similarly named elements. EX: Baby Clearance, Baby, Baby bottles, etc.
I would expect that whenever an element contains the search term at all, it should not be "hidden" with the .hide class applied.

**Additional context**

https://codesandbox.io/s/using-material-design-with-react-dropdown-tree-select-9sdiq

Search for 'iway'. Notice that you get iway child and parent but parent is "hidden".

**Comment by mrchief** [comment]
> I am returned some items that contain the search term but they are hidden with the .hide class.

Not hidden, but translucent. 
```
.node.match-in-children.hide .node-label {
  opacity: .5;
}
```
![image](https://user-images.githubusercontent.com/781818/65476189-11dda880-de50-11e9-8ac1-25b5993404fe.png)

You're seeing this effect since you're passing `keepTreeOnSearch` property. When you pass this property, the dropdown shows you ancestry of all matched nodes. Yours happens to have the same keyword in one of the parent nodes which is why this confusion arises.

Now, if you don't pass that property, you get what you're asking for albeit as a flat list:

![image](https://user-images.githubusercontent.com/781818/65476357-a0eac080-de50-11e9-8492-ca70e0e82ca6.png)

It's an interesting case and one that I haven't considered before. Quickfix, you can override this effect by adding your own css. All you have to do is ensure your CSS has higher specificity which can be achieved by adding a `className`. 

```

.custom .node.match-in-children.hide .node-label {
  opacity: 1;
}
```

![image](https://user-images.githubusercontent.com/781818/65476467-15256400-de51-11e9-96e2-16ffe068088e.png)

https://codesandbox.io/s/using-material-design-with-react-dropdown-tree-select-ux38u

Long term, the code should probably check if the node is a direct match and if so, take out the translucent effect. If you'd rather keep the translucent feature, then code fix is the only way to go. 

I can look into it if you don't mind waiting. If you want something sooner, I'd say sending a PR might be the quickest!

**Comment by sniggitysnax** [comment]
I do see that I can override the .hide style OR flatten the relationship so all appear at opacity: 1.

The issue I'm running into is that the relationship is of high importance in the UI. I want to be able to maintain the relationship hierarchy while also setting opacity to .5 to all non-relevant returned data elements.

I'll keep tabs on this feature request and open a PR if I can get around to it. I appreciate it!

**Comment by mrchief** [comment]
@sniggitysnax try v2.1.1, it should be fixed now.
