### ISSUE TITLE
Get rid of UNSAFE_ warnings in browser console

### ISSUE THREAD

**Issue by Sunphinx** [dowjones/react-dropdown-tree-select#292]
**Is your feature request related to a problem? Please describe.**
The library gives this warning to browser console:
"backend.js:6 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details."

and:

backend.js:6 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

**Describe the solution you'd like**
To get rid of the warnings in console, I see there is two solutions: either move using react hooks (react version 16.8) and replace the lifecycle methods by useEffect, or add the UNSAFE -prefix before the lifecycle methods (more information: https://fb.me/react-async-component-lifecycle-hooks). 

To reproduce: use the component and open browsers console. I'm not sure if this warning comes with older react versions but the one i'm using is 16.9.0.

**Describe alternatives you've considered**
-

**Additional context**
![image](https://user-images.githubusercontent.com/5960764/65603315-1b7d2280-dfae-11e9-9e4a-a3fefd27c117.png)

**Comment by mrchief** [comment]
You're getting these warnings because you're using a newer React version. This is just a deprecation warning and the component should work as expected. 

Moving to React 16.8+ will be a backward-incompatible change. It forces every user of this lib to upgrade. 

There are plans to move towards hooks in the next major version upgrade (v3.0) which will require React 17 as a peer dependency.

**Comment by mrchief** [comment]
Also, note that you'll not see these warnings in the production version of React. These warnings are shown during the development version to nudge folks about upcoming changes.
