### ISSUE TITLE
setState toggle problem

### ISSUE THREAD

**Issue by aseroj** [dowjones/react-dropdown-tree-select#32]
when I try to setState on `onChange`, checked values disappear.
i think there is a similar issue noted [here](https://github.com/mui-org/material-ui/issues/2983).

**Comment by h0rm** [comment]
this is probably same issue as mine [`here`](https://github.com/dowjones/react-dropdown-tree-select/issues/31). `componentWillReceiveProps` uses the `data` prop to recreate the tree every time `setState` is called in the parent component

**Comment by aseroj** [comment]
@h0rm, your Fork works perfectly
can you open a pull request so this builds into the master and so the `npm` ?
@mrchief is it possible to have this merged ?

**Comment by h0rm** [comment]
not sure if this is the right way to do this. should at least check if the whole tree has not changed by using some deep compare method...

**Comment by mrchief** [comment]
@h0rm @aseroj Yes both issues are related. And to keep the discussions in one place, let's use this thread.

@aseroj - `onChange` returns you the updated node which you can use to update your parent data - if you plan to use `setState` and be able to preserve your selection. At first, it may sound and feel counter-intuitive and simply a pain. 

But the reason it is so is because:

 - Checking just for the top level equality `this.props.data != this.state.data` is not a real proof that data has not changed. The only true way to ensure that is to perform a deep equality check which brings us to the next concern

 - Performance hit: deep equality check is not cheap. For larger trees, it is going to have a bigger impact. Because speed and performance are a key design factor with this control, I decided to not do that.

 - Recreating tree also destroys all previous search memoizations

In short, if your tree is small, you can probably get away with it. If your tree is huge (which is really what this control was built to handle), these hits add up.

If you have any ideas as to how this can be managed without taking a performance hit, I'd love to hear them.

@h0rm Is there a reason why your parent is setting state on child, even though the data has not changed? And for some reason, if you can't change that, and don't mind taking the performance hit of deep equality check, you can create a wrapper component to handle your case.

Something like (pseudo code)

```
class Wrapper extends Component {
  componentWillReceiveProps (nextProps) {
    if (data has not changed) {
      this.setState({data: nextProps.data})
    }
  }

  render () {
    return <DropdownTreeSelect {...props} data={this.state.data} />
  }
}
```

**Comment by h0rm** [comment]
The problem is even if I don't change the prop (e.g. with const data) whenever I set the state of the parent `componentWillReceiveProps` is called for the child and resets the component. I tried this on a minimal example and the React documentation even says `componentWillReceiveProps` can be called anytime.

Example `App.js` created with `create-react-app` script only `react-dropdown-tree-select` added as package with yarn:

`import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

import '../node_modules/react-dropdown-tree-select/dist/styles.css'
import DropdownTreeSelect from 'react-dropdown-tree-select'

const tree = {
  "label": "search me",
  "value": "searchme",
  "children": [
    {
      "label": "search me too",
      "value": "searchmetoo",
      "children": [
        {
          "label": "No one can get me",
          "value": "anonymous"
        }
      ]
    }
  ]
}


class App extends Component {
  state = {
    test: 'hello',
  }
  onChange = (currentNode, selectedNodes) => {
    this.setState({test: 'something else'})
    console.log('onChange::', currentNode, selectedNodes)
  }
  render() {
    return (
      <div className="App">
        <DropdownTreeSelect data={tree} onChange={this.onChange} />
      </div>
    );
  }
}

export default App;
`

**Comment by h0rm** [comment]
@mrchief  since `componentWillReceiveProps` is also called for the children the wrapper does unfortunately not work. Just tried it on the minimal example above with: 
```JSX
class DropdownWrapper extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      ...props
    };
  }
  componentWillReceiveProps (nextProps) {
    if (nextProps.data !== this.state.data) { // implement your data check here - be it deep equal or just a simple top level check
      this.setState({data: nextProps.data})
    }
  }

  render () {
    return <DropdownTreeSelect {...this.state} />
  }
}
```

**Comment by mrchief** [comment]
@h0rm When you call `setState`, react will invoke `render` - that's by design. In your example code, you can prevent that by implementing `shouldComponentUpdate` where you check the data and determine if the component should be rendered. 

Here's a working example: https://codesandbox.io/s/v05klkn56l

**Comment by mrchief** [comment]
@h0rm @aseroj does this approach solve your problem?

**Comment by aseroj** [comment]
@mrchief yes. thanks for the solution.

**Comment by shepparddean** [comment]
> @h0rm When you call `setState`, react will invoke `render` - that's by design. In your example code, you can prevent that by implementing `shouldComponentUpdate` where you check the data and determine if the component should be rendered.
> 
> Here's a working example: https://codesandbox.io/s/v05klkn56l

This helped alot, thank you.

**Comment by angrybaget** [comment]
totally  disgusting library. and i want to beat Facebook devs for creating react
why we need to use treeview, if we can't save state of it

**Comment by ravishankar1308** [comment]
**It's work with useMemo**

import React, {useMemo, useState} from 'react';

const App =() =>{

const [selectedData,setSelectedData] = useState([])

    const DropDownTreeSelect= useMemo(()=>{
   return(
       <DropdownTreeSelect
            data={treeData}
            onChange={(currentNode, selectedNodes)=>{
                setSelectedData(selectedNodes)
            }}
            className="bootstrap-demo"
            texts={{ placeholder: '' }}
        />
        )
    },[treeData])

return (
<div>
<div>{JSON.stringify(selectedData)}</div>
{DropDownTreeSelect}
<div>
)
}

**Comment by dimakruhlyi** [comment]
@ravishankar1308 this example doesn't work

**Comment by matrixmandeep** [comment]
I'm having the same problem where useState isn't working and if I use it, the checkbox values disappear.
