### ISSUE TITLE
How to set the tabindex on tree select?

### ISSUE THREAD

**Issue by Arun-Ravi** [dowjones/react-dropdown-tree-select#339]
Is there any property for setting the tabindex on tree select?

**Comment by mrchief** [comment]
Do you mean something like `<DropdownSelect tabIndex=n />` and then it reflects the `tabIndex` on the Input (or something else)?

**Comment by Arun-Ravi** [comment]
@mrchief Yes.

**Comment by mrchief** [comment]
If it's on the input, I think it's doable. Would you like to send a PR?

**Comment by ellinge** [comment]
I'm guessing it's this value. The trigger/wrapper of the dropdown.
https://github.com/dowjones/react-dropdown-tree-select/blob/develop/src/trigger/index.js#L39

**Comment by mrchief** [comment]
It starts from there but needs to be trickled to the input.

**Comment by ellinge** [comment]
It’s applied to the tabbable trigger/wrapper, a.k.a, the a-tag and not the input.

**Comment by mrchief** [comment]
Right, but does that bring the focus to the input or does it need another tabbing? Further, assigning to `0` is troublesome in a form/page since it may not be the desired index. In other words, I see it as 2 part change:

 - remove the hardcoded 0 and take it as a input prop (defaulting to 0)
 - check to see if we need to trickle it to the input box and whether it's a good idea

**Comment by mrchief** [comment]
Fixed by #439

**Comment by paycorchauhan** [comment]
@mrchief  what version will include this change ? Will it be possible to release this since latest 2.5.1 version is missing it.

**Comment by mrchief** [comment]
@paycorchauhan let me check. Will release a new version if that's the case.
