### ISSUE TITLE
Set where to Render the Tree

### ISSUE THREAD

**Issue by mesopa** [dowjones/react-dropdown-tree-select#342]
**The Problem**
It's not easy to customize the right side vertical scroll bar if the content overflows. I'm always restricted to the browser default.

**Solution**
Declare where the tree can be rendered using props or what HOC I want to use to wrap the tree.

**Alternatives**
Use a simple and light customizable scroll component, like the one available inside the following link https://github.com/AlexSergey/react-customscroll

**Additional**
Thank you for your time and great work.

**Comment by mrchief** [comment]
> It's not easy to customize the right side vertical scroll bar if the content overflows. I'm always restricted to the browser default.

Are you looking to style the scrollbar?

> Declare where the tree can be rendered 

Can you elaborate this a bit? Do mean into your own div or some other container? Or something else?

**Comment by mesopa** [comment]
![scroll](https://user-images.githubusercontent.com/6706294/75547227-691e1f80-5a65-11ea-8557-23d1e95ce1f5.png)

Left side: Chrome, Right side: Firefox

> Are you looking to style the scrollbar?

Yes, find a way to get a scrollbar that will keep the same appearance on any browser. CSS is not enough to guarantee the same appearance along all know modern browsers. 

> Can you elaborate this a bit? Do mean into your own div or some other container? Or something else?

We could choose two paths. separate the search **INPUT** from the tree **UL** or add an easy way to pass inside the component react-dropdown-tree-select, using props, a component to warp the **UL**.
I could go to an extreme and create two react-dropdown-tree-select components, one showing only the search **INPUT** and another one showing only the **UL**, but that could kill all the speed optimizations that your team achieved. The library that was mentioned before is a very light solution, creating a scroll when necessary, with a uniform appearance, but I don't have a way to wrap around the **UL**.

**Comment by mrchief** [comment]
Ok I see what your concerns are. 

> Yes, find a way to get a scrollbar that will keep the same appearance on any browser. CSS is not enough to guarantee the same appearance along all know modern browsers.

One might equally argue that keeping the same appearance everywhere is not a good idea since people are accustomed to the native browser's scroll experience and would expect the same. 

Regardless of the school of thought, it's a **choice** for the developer who's building the UI and as a white-labeled component, I do not want to make the choice for the user. 

> We could choose two paths. separate the search INPUT from the tree UL or add an easy way to pass inside the component react-dropdown-tree-select, using props, a component to warp the UL.

We're creating more moving parts and bringing in complexity but let's keep this under consideration for now, which brings us to your other point:

>  I could go to an extreme and create two react-dropdown-tree-select components, one showing only the search INPUT and another one showing only the UL, but that could kill all the speed optimizations that your team achieved. 

True and that'd be a ugly solution which I dislike just as much as you do. :)

> The library that was mentioned before is a very light solution, creating a scroll when necessary, with a uniform appearance, but I don't have a way to wrap around the UL.

I appreciate you understanding the choices we have made so far and willing to work with them. So let's see if we can find a middle ground that achieves what you're trying to achieve without adding more moving parts (if possible) or requiring hacky solutions.

As one possible idea, say if we were to restructure the HTML layout, would this be possible with just CSS? Changing the layout is going to be a breaking change as that would interfere with any existing styles that the component's users' might be using right now. However, it still is a good solution as it leaves the **choice** in the hands of the end developer. 

Another possible idea is to seek a JS based solution and I'd like to hear what other people think about it before arriving to any conclusion.

Last but not the least, I'd love to hear any other ideas you might have on solving this, in the light of above discussion.

**Comment by mesopa** [comment]
First of all, I want to thank you very much for your time and I also glad to share how I solved my request.

In this case, I wrapped tree-component inside the custom-scroll-component and with some CSS tweaks I ended up with the intended result without modifying any core part of the react-dropdown-tree component.

![image](https://user-images.githubusercontent.com/6706294/77884343-72ceb900-7297-11ea-95a2-e32b3ae10cec.png)

Bellow, I share the code sandbox where I demonstrate the achievement:
[Sandbox Test](https://codesandbox.io/s/zen-hooks-69ws2)

Thank you very much.

**Comment by mrchief** [comment]
@mesopa That's great! Would you like to showcase your work on the main doc site? https://dowjones.github.io/react-dropdown-tree-select/#/story/readme

**Comment by smurfs2549** [comment]
If I did not hide 'dropdown-trigger', how does this function work? SearchInput height is a stable value, we can set 'transform: translateY(-2.875rem)' and absolute position. But I need show 'dropdown-trigger' and the container height is changed when the value changed.

**Comment by mrchief** [comment]
@smurfs2549 Is it possible to create a codesandbox? You can fork the one above and maybe add your changes there?

**Comment by smurfs2549** [comment]
https://codesandbox.io/s/cocky-archimedes-feecm
I don't want to hide the selected elements list and search input shouldn't set position to absolute.
I don't want to scroll all the content. I just want to scroll dropdown-content.
 @mesopa 's solution is useful for hide selected element that doesn't make sense for show selected element.

**Comment by mrchief** [comment]
@smurfs2549 I thought your original issue was to add a 3rd party package. But it seems you were trying that because dropdown scroll wasn't working using keyboard?

Mouse and Keyboard navigation work fine if you try out the basic demo: https://dowjones.github.io/react-dropdown-tree-select/#/story/basic-no-extra-styles

If it's not working for you, then can please open an issue with a CodeSandbox to reproduce it?

**Comment by smurfs2549** [comment]
yes. If I not add a 3rd party package(simplebar-react or react-customscroll),  Keyboard navigation work fine. But I want add simplebar-react to change scrollbar style, because on IE it seems not good. Like#352.
