### ISSUE TITLE
dropdown-content add simplebar the keyboardNavigation not works correctly

### ISSUE THREAD

**Issue by smurfs2549** [dowjones/react-dropdown-tree-select#352]
**the dropdown scrollbar style is not good on IE browser**
So I use 'simplebar' package to change scrollbar style, but I can't scroll it use the keyboard.

**Describe the solution you'd like**
That is perfect if this package can add 'react-simplebar' and the keyboard navigation works correctly.

![image](https://user-images.githubusercontent.com/8286468/78095828-8d756f00-740a-11ea-8374-dbe1cd181997.png)

expect on IE:
![image](https://user-images.githubusercontent.com/8286468/78095885-ba298680-740a-11ea-8044-6f3142fe52f6.png)

**Comment by mrchief** [comment]
@smurfs2549 I'm not going to add a package to customize scrollbar due to reasons discussed [before](https://github.com/dowjones/react-dropdown-tree-select/issues/342#issuecomment-592557937). 

It seems you can do so without modifying the component, take a look at the user land solution [here](https://github.com/dowjones/react-dropdown-tree-select/issues/342#issuecomment-605820493).
