### ISSUE TITLE
Disable `coveralls` invocation on forked repositories

### ISSUE THREAD

**Issue by mobilutz** [dowjones/react-dropdown-tree-select#397]
**Describe the bug**
Within forked repositories it is possible to run TravisCI runs, but there is always a `coveralls` failure.
Please disable coveralls invocation when CI runs on forks.

As an idea:
* run all JS tests on branches and pull-requests
* only run coveralls on pull-requests (which will always be on this repository)

**Comment by mrchief** [comment]
> only run coveralls on pull-requests (which will always be on this repository)

this is the thing though - unless the branch exists on this repo, the PR's branch will be on a personal fork and sharing secrets to external forks is a not a good idea since you expose yourself to potential theft of secrets. This is why GH actions don't do it. Travis + Coveralls works differently in that the code is forked to their servers and tests are run there and results are reported back. 

I feel like something got broken when I was trying to get rid of Travis and then had to re-enable it because I wanted coveralls. So I have a feeling that just revisiting tokens and making sure we have the proper ones added, will fix this issue.

That said, now I'm wondering - did it ever work? If not, then I might be trying to solve an impossible to solve issue. :)

**Comment by mrchief** [comment]
Github has introduced `pull_request_target` event which can help towards this. I've been swamped at work lately so I'll try it our when I have some time or if you wanna try it and send a PR, please feel free to do so,
