### ISSUE TITLE
Add possibility to get number of end selected items also all end items

### ISSUE THREAD

**Issue by VadimN92** [dowjones/react-dropdown-tree-select#454]
**Would be great to show for user how many selected end items.**
P1-|-C1            (P1 children count 3, and 2 without children)
      |-C2
      |-P2-|-C1       (P2 children count 5, and 3 without children)
               |-C2
               |-P3-|-C1  (P3 children count 2)
                        |-C2
               |-C3
               |-C4
               |-P4-|-C1   (P4 children count 2)
                        |-C2

If P2 selected so all children also. Will be good to have sum of end items and sum all of end children. 
I don't know for sure, but it may already be possible to get this number of items.

**Comment by mrchief** [comment]
This is highly specific logic (to your particular use case). I think once we have the headless version ready, you should be able to accomplish this easily.

**Comment by mrchief** [comment]
> Is it actually already possible to add a simple count next to the items, similarly to what you are doing with the country flags? 

It is possible and in few different ways. Without modifying anything in the component, you can pass in a class name and do it via css. An HOC can generate the count based on data and tack on those additional classes, similar to the country flag logic. It'll be bit tedious since you'd need lot of CSS classes with different counts but this will be a one time setup and you can generate those classes with bit of scripting so it's probably manageable. 

An different way would require the component to emit a count - either via a data attribute or some other way - it either becomes part of the HTML and is hidden for most that don't need it and those who need it can toggle it via CSS. This requires changes to the component and adds a bit of logic & complexity as it needs to keep track of count. This is slightly less desirable as everyone now has to bear that performance hit even if they don't need it. 

This sort of logic is the ideal use case for headless components where you can bring in your own UI logic and not affect others but his requires a lot of changes in the component. I'd like this to move towards a headless world but haven't had the time to do so.

Those are all the ways I can think of, starting with the quickest, least ideal to the longest, most ideal way of doing this.

**Comment by TimMcCauley** [comment]
Thank you @mrchief - I will give the dynamic CSS approach a go and will report back!
