### ISSUE TITLE
Custom search term to be passed as prop

### ISSUE THREAD

**Issue by shubhamk54** [dowjones/react-dropdown-tree-select#462]
Is there a way to pass the search term to the component like:

` <DropdownTreeSelect
             searchTerm={'Some Name'}
            />`

So the data list will be filtered based on the custom search text which component will receive as a prop.

**Comment by mrchief** [comment]
What is the use case here - you'd be setting setting term outside and use the component to display filtered results only?

If that's the case, you can do that using an HoC. The default [searchPredicate](https://github.com/dowjones/react-dropdown-tree-select#searchpredicate) is a simply indexOf search:

```
return node.customData && node.customData.toLower().indexOf(searchTerm) >= 0
```

So you can use composition to create a HoC that:
 - accepts `data`, `searchTerm`
 - filters `data` based on the `searchTerm` 
 - assigns `filteredData` to the component
 - set `showDropdown="initial"` so that it opens up the dropdown on initial render
