### ISSUE TITLE
Child nodes appear to be rendered under wrong parent

### ISSUE THREAD

**Issue by computas-ai** [dowjones/react-dropdown-tree-select#488]
Hi! I've been trying out this package over the few days and it seems to be something we're wanting to use in our project. I do however have som issues with expanding child nodes, as some of the nodes seems to be rendered under the wrong parent node. In the picture I expect the nodes under "Innlandet" to be rendered under their expanded parent "Møre og Romsdal". If I expand "Innlandet" and its first child, the nodes that should be under "Møre og Romsdal" sort of merges with the children under the wrong parent. I am unsure what causes this, and it seems to only be a problem with parents that has 2 or more expandable children.

Is this a result of bad css of sorts? Or is it a problem with the model maybe? I am quire unsure of how to attack this problem.

How I render the DropdownTreeSelect:

``` 
const renderTree = useMemo(() => {
    return (
      state.locationCodes && (
        <DropdownTreeSelect
          data={state.locationCodes.children} // Skip top level node
          texts={{ placeholder: t('component_select_default_value') }}
          onChange={onChange}
          keepTreeOnSearch
        />
      )
    );
  }, [state.locationCodes]);
```
  
  The datatype that I feed into the DropdownTreeSelect:
```
export interface Location {
    id: string;
    value?: string;
    label: string;
    children: Location[];
    checked?: boolean;
}
```

Pastebin with data I recieve from backend: https://pastebin.com/Ek8ncAUj

Any help would be very much appreciated!

![bilde](https://user-images.githubusercontent.com/55973383/121013680-71512880-c799-11eb-8fdc-fc112a70c545.png)

**Comment by mrchief** [comment]
Based on the data, I can see that some ids are duplicated. 

![image](https://user-images.githubusercontent.com/781818/121268539-2b28c180-c88c-11eb-9257-7ea261ff09a5.png)

If you're providing `id` within the data object, the component will try to use that instead of assigning its own unique ids. That could lead to the behavior that you're experiencing. I tried renaming a few ids to make them unique and as you can see, the disappear from under `Innlandet` after that.

![image](https://user-images.githubusercontent.com/781818/121268623-50b5cb00-c88c-11eb-9fed-14d185d08e49.png)

Here's a codesandbox if you want to play around 
https://codesandbox.io/s/react-dropdown-tree-select-forked-humt2

**Comment by computas-ai** [comment]
You are absolutely correct. I took a closer look at the data and saw the entries with duplicate id. It was fixed on backend and now it works like a charm. Thanks a lot for pointing this out, and sorry for bothering you.

**Comment by mrchief** [comment]
No worries! Glad it all worked out!
