### ISSUE TITLE
Dropdown component does not change to disabled when disabled={state} is changed

### ISSUE THREAD

**Issue by jacobtyq** [dowjones/react-dropdown-tree-select#528]
**Describe the bug**
I have the react-dropdown-tree-select component with the `disabled` flag tied to a `useState` that is controlled by another component. When I change the state from 'true' to 'false' or vice versa, the dropdown does not get disabled/enabled.

I am using a HOC similar to [Prevent re-render on parent render with React Dropdown Tree Select](https://codesandbox.io/s/v05klkn56l?from-embed)

**To Reproduce**
https://codesandbox.io/s/changing-states-do-not-affect-react-dropdown-tree-select-eouow

**Expected behavior**
The dropdown component should change from disabled to enabled state and vice versa.

**Additional context**
react-dropdown-tree-select@^2.5.1

**Comment by mrchief** [comment]
> I am using a HOC similar to

Sounds like the HOC is preventing the re-render on state change. You need to explicitly allow for `disabled` flag to pass through https://codesandbox.io/s/changing-states-do-not-affect-react-dropdown-tree-select-forked-234j2?file=/src/DropdownContainer.js

**Comment by jacobtyq** [comment]
> HOC is preventing the re-render on state change

The solution works! 👍  

Is there a reason for HOC preventing the re-render? I'm not using `React.memo` that would prevent re-renders .

**Comment by mrchief** [comment]
> Is there a reason for HOC preventing the re-render?

The tree maintains it own state and applies memoization to optimize for repeated searches. If your dataset is big, recreating the whole tree can take a lot of time and it is more wasteful if your data didn't really change. If you re-render the component, you lose some potential performance benefits which is why you'd want to prevent the re-render. React.memo is the functional/hooks equivalent of preventing unwanted re-renders. I'm going to close the issue but feel free to keep the discussion going.
