### ISSUE TITLE
question: embed some node info on tag

### ISSUE THREAD

**Issue by Gregcop1** [dowjones/react-dropdown-tree-select#53]
The idea is to have children and leaf count on each node and to embed those infos on node and tag items via custom attributes ("data-nb-children", "data-nb-leaf" for ex.) so user can display them with a bit of css if he need it.

Displaying something like that 
![capture d ecran de 2018-02-26 15-41-18](https://user-images.githubusercontent.com/1257968/36676476-17918796-1b0c-11e8-986f-946f7ee4b1fd.png)
is done via `content: "("attr(data-nb-leaves)")";`

I don't know if you want something like that in your module but if so, I've got a PR for you ;)

**Comment by mrchief** [comment]
The component already preserves any extra props you pass on the node and bubbles it back in the event handlers. I guess taking (a bunch of them?) and emitting them as data attributes is probably not a big issue from performance or code complexity standpoint. 

I think emitting everything is probably not a good idea (mainly because it just makes the generated HTML chatty for no apparent gains). So, if we can restrict the attributes to be emitted to some prop, I think it makes for a simpler, opt-in kinda approach. 

I'm open to this. Sounds like a good to have thing.
