### ISSUE TITLE
Styles is not included by default

### ISSUE THREAD

**Issue by Charlie91** [dowjones/react-dropdown-tree-select#8]
Hello.
Thank you for your useful library.
I have found a possible issue. When i include your lib in my React.Component it has not any style within itself.
So, it requires to import additional styles which i took from node_modules;

**Comment by mrchief** [comment]
@Charlie91 This is by design. Default styles are provided and it is up to the user to use them or not. This is to allow easy swapping of default styles with your own. Not importing default styles also gives flexibility to bundle styles based on the bundler you're using, instead of forcing you to use one specific bundler.

Last but not least, by doing selective import, you can also benefit from code splitting and bundle size optimizations thereof.

You can also do a global import or reference it in your app.jsx - although not recommended. Instead, if you want to include it globally, I'd suggest to create a [vendor bundle](https://webpack.github.io/docs/code-splitting.html#split-app-and-vendor-code) and reference that in your main page.
